# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build apollo-graphql-boilerplate`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t apollo-graphql-boilerplate`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system apollo-graphql-boilerplate && \
          adduser --system -G apollo-graphql-boilerplate apollo-graphql-boilerplate

COPY dist/apollo-graphql-boilerplate apollo-graphql-boilerplate
RUN chown -R apollo-graphql-boilerplate:apollo-graphql-boilerplate .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix apollo-graphql-boilerplate --omit=dev -f install

CMD [ "node", "apollo-graphql-boilerplate" ]
